"""Main CLI entry point using Click framework."""

from __future__ import annotations

import sys
from pathlib import Path

import click

from agentcanvas_cli import __version__


@click.group()
@click.version_option(version=__version__)
def cli() -> None:
    """AgentCanvas CLI - Manage your AgentCanvas installation."""
    pass


@cli.command()
@click.option(
    "--dir",
    default=".",
    help="Directory to initialize (default: current directory)",
    type=click.Path(),
)
@click.option(
    "--db",
    type=click.Choice(["sqlite", "postgresql"]),
    default="sqlite",
    help="Database backend (default: sqlite)",
)
def init(dir: str, db: str) -> None:
    """Initialize AgentCanvas configuration in a directory.

    Creates .env file with default configuration and generates
    required secret keys.
    """
    target_dir = Path(dir).resolve()
    env_file = target_dir / ".env"

    if env_file.exists():
        click.confirm(
            f".env already exists in {target_dir}. Overwrite?",
            abort=True,
        )

    # Generate secret key
    import secrets
    secret_key = secrets.token_urlsafe(32)

    # Create .env content
    env_content = f"""# AgentCanvas Configuration
# Generated by: agentcanvas init

# Database
DATABASE_URL={"sqlite:///./agentcanvas.db" if db == "sqlite" else "postgresql://user:pass@localhost/agentcanvas"}

# Security
SECRET_KEY={secret_key}

# Server
HOST=0.0.0.0
PORT=8000

# Frontend
FRONTEND_URL=http://localhost:5173

# Redis (optional, for distributed execution)
# REDIS_URL=redis://localhost:6379/0

# LLM Provider API Keys (add as needed)
# ANTHROPIC_API_KEY=
# OPENAI_API_KEY=
# GEMINI_API_KEY=
# MISTRAL_API_KEY=
# COHERE_API_KEY=

# MCP Server Tokens (add as needed)
# GITHUB_TOKEN=
# SLACK_BOT_TOKEN=
# NOTION_TOKEN=
"""

    env_file.write_text(env_content, encoding="utf-8")
    click.echo(f"✓ Created .env in {target_dir}")
    click.echo(f"✓ Database: {db}")
    click.echo(f"✓ Secret key generated")
    click.echo("\nNext steps:")
    click.echo("  1. Edit .env to add your API keys")
    click.echo("  2. Run 'agentcanvas migrate' to set up the database")
    click.echo("  3. Run 'agentcanvas dev' to start the development server")


@cli.command()
@click.option(
    "--host",
    default="0.0.0.0",
    help="Host to bind (default: 0.0.0.0)",
)
@click.option(
    "--backend-port",
    default=8000,
    help="Backend port (default: 8000)",
)
@click.option(
    "--frontend-port",
    default=5173,
    help="Frontend port (default: 5173)",
)
@click.option(
    "--no-frontend",
    is_flag=True,
    help="Start backend only, skip frontend",
)
def dev(host: str, backend_port: int, frontend_port: int, no_frontend: bool) -> None:
    """Start AgentCanvas development server (frontend + backend).

    Launches both the FastAPI backend and Vite frontend in development mode.
    Press Ctrl+C to stop both servers.
    """
    import subprocess
    import os

    # Find project root
    current = Path.cwd()
    backend_dir = current / "backend"
    frontend_dir = current / "frontend"

    if not backend_dir.exists():
        click.echo("Error: backend/ directory not found", err=True)
        click.echo("Run this command from the AgentCanvas project root", err=True)
        sys.exit(1)

    processes = []

    try:
        # Start backend
        click.echo(f"Starting backend on {host}:{backend_port}...")
        backend_env = os.environ.copy()
        backend_env["HOST"] = host
        backend_env["PORT"] = str(backend_port)

        backend_proc = subprocess.Popen(
            ["uv", "run", "uvicorn", "app.main:app", "--reload",
             "--host", host, "--port", str(backend_port)],
            cwd=str(backend_dir),
            env=backend_env,
        )
        processes.append(backend_proc)
        click.echo(f"✓ Backend started (PID {backend_proc.pid})")

        # Start frontend
        if not no_frontend:
            if not frontend_dir.exists():
                click.echo("Warning: frontend/ directory not found, backend only", err=True)
            else:
                click.echo(f"Starting frontend on port {frontend_port}...")
                frontend_env = os.environ.copy()
                frontend_env["PORT"] = str(frontend_port)

                frontend_proc = subprocess.Popen(
                    ["pnpm", "dev", "--port", str(frontend_port)],
                    cwd=str(frontend_dir),
                    env=frontend_env,
                )
                processes.append(frontend_proc)
                click.echo(f"✓ Frontend started (PID {frontend_proc.pid})")

        click.echo("\n" + "=" * 50)
        click.echo("AgentCanvas Development Server Running")
        click.echo("=" * 50)
        click.echo(f"Backend:  http://{host}:{backend_port}")
        if not no_frontend:
            click.echo(f"Frontend: http://localhost:{frontend_port}")
        click.echo(f"API Docs: http://{host}:{backend_port}/docs")
        click.echo("\nPress Ctrl+C to stop")
        click.echo("=" * 50 + "\n")

        # Wait for processes
        for proc in processes:
            proc.wait()

    except KeyboardInterrupt:
        click.echo("\n\nShutting down...")
        for proc in processes:
            proc.terminate()
        for proc in processes:
            proc.wait(timeout=5)
        click.echo("✓ Stopped all servers")


@cli.command()
@click.option(
    "--revision",
    default="head",
    help="Target revision (default: head for latest)",
)
def migrate(revision: str) -> None:
    """Run database migrations using Alembic.

    Applies pending migrations to bring the database schema up to date.
    """
    import subprocess

    current = Path.cwd()
    backend_dir = current / "backend"

    if not backend_dir.exists():
        click.echo("Error: backend/ directory not found", err=True)
        sys.exit(1)

    click.echo(f"Running migrations to revision: {revision}")

    try:
        result = subprocess.run(
            ["uv", "run", "alembic", "upgrade", revision],
            cwd=str(backend_dir),
            check=True,
            capture_output=True,
            text=True,
        )
        click.echo(result.stdout)
        click.echo("✓ Migrations completed successfully")
    except subprocess.CalledProcessError as e:
        click.echo(f"Error running migrations:\n{e.stderr}", err=True)
        sys.exit(1)


@cli.command()
@click.option(
    "--output",
    default="agentcanvas_backup.tar.gz",
    help="Backup file path (default: agentcanvas_backup.tar.gz)",
)
@click.option(
    "--include-data/--no-include-data",
    default=True,
    help="Include database data (default: yes)",
)
def backup(output: str, include_data: bool) -> None:
    """Create a complete backup of AgentCanvas installation.

    Backs up:
    - Database (SQLite file or PostgreSQL dump)
    - Configuration files (.env)
    - Uploaded files and attachments
    """
    import subprocess
    import tarfile
    import tempfile
    from datetime import datetime

    current = Path.cwd()
    backend_dir = current / "backend"
    output_path = Path(output).resolve()

    if not backend_dir.exists():
        click.echo("Error: backend/ directory not found", err=True)
        sys.exit(1)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    click.echo(f"Creating backup: {output_path}")

    with tempfile.TemporaryDirectory() as tmpdir:
        backup_dir = Path(tmpdir) / f"agentcanvas_backup_{timestamp}"
        backup_dir.mkdir()

        # Backup .env
        env_file = current / ".env"
        if env_file.exists():
            import shutil
            shutil.copy2(env_file, backup_dir / ".env")
            click.echo("✓ Backed up .env")

        # Backup database
        if include_data:
            db_file = backend_dir / "agentcanvas.db"
            if db_file.exists():
                import shutil
                shutil.copy2(db_file, backup_dir / "agentcanvas.db")
                click.echo("✓ Backed up SQLite database")
            else:
                click.echo("Note: No SQLite database found", err=True)

        # Create tar.gz
        with tarfile.open(output_path, "w:gz") as tar:
            tar.add(backup_dir, arcname=backup_dir.name)

        click.echo(f"✓ Backup created: {output_path}")
        click.echo(f"  Size: {output_path.stat().st_size / 1024 / 1024:.2f} MB")


def main() -> None:
    """Main entry point."""
    cli()


if __name__ == "__main__":
    main()
